apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: opjorr/dining-backend:latest
  newName: opjorr/dining-backend
  newTag: d47c9a6ebbea522bad657105dbadf079df0b351d
