apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yamls
images:
- name: opjorr/dining-backend:latest
  newName: opjorr/dining-backend
  newTag: 17d4ffc3fe76f5fe476fcd580017c8245bc95fac
